title: Valeria Mite
description: Bienvenidos a mi Blog
keywords: blog,css,html,php #博客关键字
author: "Link"

#title hide and show
hide: 
show: 

baseurl: "/blog6" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "davenplay.github.io" # change this to the base hostname & protocol for your site
buildtime: "1514736000" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: https://www.eluniverso.com/sites/default/files/styles/powgallery_1280/public/fotos/2018/06/universidad_de_guayaquil_24330422.jpg?itok=pV8zrxN3
theme_color: 174381

google_analytics:
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

#MathJax switch
MathJax: false

#install emoji
plugins:
  - jemoji

# social account
image:
twitter: https://mobile.twitter.com/MiteArboleda
  username:
#  site:
facebook: https://www.facebook.com/valerianatalia.mitearbolada
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
